### PR TITLE
About panel and l10n checks

### PR DESCRIPTION
**Pull request by tobozo**
- added new keys in labels.properties for AboutPanel
- refactored l10n class
- added l10n check to CI test, will trigger a [job fail & report](https://github.com/tobozo/esp32partitiontool/actions/runs/8719150934/job/23917906587) if any translation is missing

### CODE REVIEW

**Comment by tobozo** [comment]
a failed job for this PR is normal (AboutPanel translations are missing for every language except English), howewer I'm havin doubts about this line in the yaml workflow file:

    token: ${{ secrets.RELEASE_TOKEN }}

if your [Workflow permissions](https://github.com/serifpersia/esp32partitiontool/settings/actions) aren't set on **Read and write** you may need to restore the token, otherwise it isn't needed

**Comment by serifpersia** [comment]
The PR looks good for merge if you don't have anything else to add let me know.

**Comment by serifpersia** [comment]
> a failed job for this PR is normal (AboutPanel translations are missing for every language except English), howewer I'm havin doubts about this line in the yaml workflow file:
> 
> ```
> token: ${{ secrets.RELEASE_TOKEN }}
> ```
> 
> if your [Workflow permissions](https://github.com/serifpersia/esp32partitiontool/settings/actions) aren't set on **Read and write** you may need to restore the token, otherwise it isn't needed

The PR looks good for merge if you don't have anything else to add let me know. I will remove that line and see if it can build a release without issue.

**Comment by tobozo** [comment]
I have no further commits for this PR

**Comment by tobozo** [comment]
trying to advertise the new l10n support on the social networks ...

https://mastodon.social/@tobozo/112290798173744999

https://twitter.com/TobozoTagada/status/1780846712086569342

... and realized the ReadMe isn't obvious about how translators should peer-review, do you want a PR for this change?

## Issues and Contributions
Feel free to report any [issues](https://github.com/serifpersia/esp32partitiontool/issues). Translation [contributions are welcome](https://github.com/serifpersia/esp32partitiontool/tree/main/src/main/resources/l10n) if you find the [current translations](https://github.com/serifpersia/esp32partitiontool/blob/main/src/main/resources/l10n/labels.properties) to be wrong, not adequate or you want to add support for another language.

**Comment by tobozo** [comment]
btw I made a plugin to declutter the boards list in Arduino IDE 1.8.x (doesn't apply to platformio or vscode), I'd be happy to have your feedback ^^

https://github.com/tobozo/Arduino-Hidden-Boards-Manager

**Comment by serifpersia** [comment]
I will update the readme. I will look at your repo to see whats up :). Edit: Looks fairly easy to navigate and look at. Maybe improve the about panel there is a lot of empty space below the image maybe make the image bigger and center it at least.

**Pull request merged**
