### PR TITLE
Bugfix + UI improvement

### PR DESCRIPTION
**Pull request by tobozo**
- changed the text alignment to RIGHT for hex/dec values 
- changed the text font to monospace for hex/dec values
- removed unnecessary check in `importCSV()`
- added helper functions to improve values parsing

image

This is a draft PR, more commits will be added soon.

Next tasks:

- [x] LittleFS support
- More UI improvements 
    - [x]  right/bottom margin/padding
    - [x]  partitions graph needs to be improved e.g. add hint to partition type
    - [x]  ~~remove flash/merge buttons (redundant with the IDE)~~

### CODE REVIEW

**Comment by serifpersia** [comment]
Looking good.As suggested, you can remove the sketch button, I assume you want to implement the littlefs/spiffs combo box selector. Since Right panel is mostly empty try to fit the controls on the bottom area if possible if not controls can be left on the right panel. I can do merge bin stuff I talked about after your changes if you want to leave that to me.

**Comment by tobozo** [comment]
I left the right panel enabled as it would make the new filesystem choice useless, every spiffs-related functionality  (label, path to binary, command line) now inherits from that combo.

Since the boot offset is now inherited from the board settings, code blocks handling esp32 and esp32s3 have been de-duplicated.

image

**Comment by tobozo** [comment]
btw I have no further commit, so you can take it from there

**Comment by serifpersia** [comment]
Fixed minor issues with the PR. It's acceptable to be pushed into the main branch. Feel free to contribute more if you find the tool can be improved more. Thanks again!

**Comment by tobozo** [comment]
whoops sorry about the whitespace mess :bow: 

the door is still open to a few unimplemented features, I'm already working on a few of those:

- [x] properly inherit from `build.partitions` board option
- [x] add inheritance from optional `build.custom_partitions` board option
- [x] perform a tools check on applet load (e.g. remove unavailable filesystems from combo when associated tool was not found in the provided path) 
- [ ] enable vertical overflow and scroll on the partition GridLayout
- [ ] make `NUM_ITEMS` vary using [+] / [-] buttons (partition can contain up to 95 x **[type=app]**)
- [x] add a preferences panel for the tools path/names (mklittlefs, mkspiffs, mkfatfs, custom)
- [ ] move the filesystem selector to the preferences panel
- [x] add a 'debug' checkbox to the preferences panel, will enable verbose output to Arduino log window

**Comment by serifpersia** [comment]
> whoops sorry about the whitespace mess 🙇
> 
> the door is still open to a few unimplemented features, I'm already working on a few of those:
> 
>     * [ ]  properly inherit from `build.partitions` board option
> 
>     * [ ]  add inheritance from optional `build.custom_partitions` board option
> 
>     * [ ]  perform a tools check on applet load (e.g. remove unavailable filesystems from combo when associated tool was not found in the provided path)
> 
>     * [ ]  enable vertical overflow and scroll on the partition GridLayout
> 
>     * [ ]  make `NUM_ITEMS` vary using [+] / [-] buttons (partition can contain up to 95 x **[type=app]**)
> 
>     * [ ]  add a preferences panel for the tools path/names (mklittlefs, mkspiffs, mkfatfs, custom)
> 
>     * [ ]  move the filesystem selector to the preferences panel
> 
>     * [ ]  add a 'debug' checkbox to the preferences panel, will enable verbose output to Arduino log window

Yeah the limited partitions has to be top priority if list of partitions is mostly over this given amount(NUM_ITEMS) Creating + - button on the left side  or bottom panel to add and remove partitions, maybe scroll panel can be used for the root JPanel layout and grid layout is fine for the ui components. What about the FATFS filesystem? Currently its giving out error tool not found maybe a do auto download script to get the tool before using it? Curl to be used for that most systems should have it installed?

**Comment by tobozo** [comment]
so far so good, here's a summary of the changes on my fork:

- added implicit find&load for the csv partition associated with the selected board
- added new checkbox to enable/disable debug
- improved context checking before writing on disk, less exception, more informative error messages
- created logic to handle mkfatfs args separately

There's no preferences panel yet, but there are preferences, saved in a properties file in the same folder as the jar file. Its content is populated automatically, and it can be edited with a text editor until the UI gets a preferences panel.

Preferences currently stored in this properties file:

  - mkspiffs.path
  - mklittlefs.path
  - mkfatfs.path
  - esptool.path
  - debug.enabled
  
Note: `*.path` properties store a full path, including the file name.

There are several possible sources to gather this information, so the order of precedence is as follows:

- path inherited from `prefs.properties` (stored with the jar file)
- path inherited from `preferences.txt` (e.g. `runtime.tools.*.path`)
- path speculated from `platform.getFolder()`
- path speculated from `BaseNoGui.getDefaultSketchbookFolder()`
- path speculated from `BaseNoGui.getToolsPath()`  (e.g. near the arduino executable)

**Pull request merged**
