### PR TITLE
l10n (localization) support

### PR DESCRIPTION
**Pull request by tobozo**
- most UI text labels have been moved to properties file in the resources/l10n folder.
- no language selector, just inherits Arduino IDE language or system default locale
- UTF8-safe, tested with different alphabets and symbol systems

Obviously English is the default language; I've added French as a first example, maybe ChatGPT could take care of more languages?

### CODE REVIEW

**Comment by serifpersia** [comment]
Yeah GPT should be good option for translating into at least few main languages, unless someone hops in and contributes most correct translation from English, mainly the about panel has bulk of the text. I will look into this PR tomorrow and provide some translation but they won't be as good as native speaker.  I could do Serbian without issues.

**Comment by tobozo** [comment]
the about panel may need a couple of changes to make sure it keeps a consistant size across languages, currently it's using html breaks to prevent horizontal expansion and the text has to be split to simulate word wrap

ideally the right side of the about panel should have a fixed width and not use htlm breaks at all

**Comment by serifpersia** [comment]
I couldn't build seems the script is broken and its not this PR its latest upstream commit have no idea what I changed for it to break... Oh I think i don't have java 8 jdk I think that has to do something with it haha.

**Comment by tobozo** [comment]
took me a couple hours to figure out I was using jdk11 too :rofl: 

if [the CI didn't complain](https://github.com/serifpersia/esp32partitiontool/actions/runs/8705205898) then it's probably a local problem

**Comment by serifpersia** [comment]
> took me a couple hours to figure out I was using jdk11 too 🤣
> 
> if [the CI didn't complain](https://github.com/serifpersia/esp32partitiontool/actions/runs/8705205898) then it's probably a local problem

I will add check to do nothing or at least display something is wrong with java jdk for build_specific scripts. Your cl scripts should work just fine my scripts for building specific tool was not able to run bc of missing jdk it just did some folder creation and extraction but no jar. Once i installed jdk 8 it worked just fine.

**Comment by tobozo** [comment]
btw I'm not sure languages not listed in [that file](https://github.com/arduino/Arduino/blob/master/arduino-core/src/cc/arduino/i18n/Languages.java) can be used in the plugin (arduino version), it seems the Arduino IDE overwrites the default system locale with its own default supported locale

**Comment by serifpersia** [comment]
I tried to do serbian display language in my windows 11 and set system default in arduino ide but it changed to english but it did work for french. I assume it won't work if the language doesn't exist in that list in arduino preferences?

**Comment by tobozo** [comment]
it should work with platformio version though, try this:


    LANG=sr java -cp /path/to/ESP32PartitionTool.jar com.platformio.ESP32PartitionToolStandalone

**Comment by serifpersia** [comment]
Oh so platformio version also has support for localization as well it has auto detect system language right? If so I could add my language properties file as well if thats the case.

**Comment by tobozo** [comment]
this is how the locale is extracted for both platformio and arduino: 

    Locale.getDefault().getLanguage()

Arduino IDE probably overrides this with English when the language isn't in the [translations list](https://github.com/arduino/Arduino/tree/master/arduino-core/src/processing/app/i18n)

**Comment by serifpersia** [comment]
No worries I verified at least for Arduino IDE it detects the language and does load the properties file correctly. If you need anything else to add feel free this is fine for merge.

**Comment by tobozo** [comment]
I'll probably make the aboutPanel localizable later in a separate PR, I have nothing to add to this PR

no peer review for the translations -> I hope the AI didn't hallucinate too much :rofl:

**Comment by serifpersia** [comment]
> I'll probably make the aboutPanel localizable later in a separate PR, I have nothing to add to this PR
> 
> no peer review for the translations -> I hope the AI didn't hallucinate too much 🤣

I worry if the text label will fit in the ui hahah. I checked for my language it was semi correct not very specific terms used but it wasn't off by a lot.

**Pull request merged**
