### PR TITLE
misc improvements

### PR DESCRIPTION
**Pull request by tobozo**
- Added implicit find&load for the csv partition associated with the selected board
- Added new checkbox to enable/disable debug
- Improved context checking before writing on disk, less exception, more informative error messages
- Created logic to handle mkfatfs args separately

Making NUM_ITEMS dynamic is like opening a pandora box so I'm submitting this before attempting anything.

### CODE REVIEW

**Comment by serifpersia** [comment]
I tried this PR commit and arduino ide doesn't detect the tool anymore. Trying to run the applet in my ide(uncomment the main func) also makes my ide go into debug/crash mode I assume something is wrong or I'm missing a file?
image

**Comment by serifpersia** [comment]
I tried to experiment with dynamic NUM_ITEMS I got the UI to work at least but there is no reaction to the interaction I assume the action listeners have to be removed and added again. Edit: Think I got to reactivity back but, I'm not going to waste my time on this. If you are interested feel free to do it but your PR is not working for me atm.
image

**Comment by tobozo** [comment]
> makes my ide go into debug/crash mode 

I have no idea how to test that on windows without spending a whole day installing and configuring Eclipse, do you have any additional clue on how/why it is crashing?

e.g. what happens in the console if you launch the arduino ide executable from an unprivileged powershell, does it print any error or stack dump?

I'm using OpenJDK 1.8.0_402.

> I assume the action listeners have to be removed and added again.

It's not mandatory in every scenario, for example it's possible to just toggle their visibility, then use ::isVisible() to identify active items when processing the list and constrain the view  to `N(:checked)+1 lines always visible`.

In such scenario the [+] / [-] buttons aren't necessary anymore, an extra line appears/disappears when the last line is checked/unchecked and the list can have a fixed length of 100 elements (max 95 [type=app] entries).

**Comment by tobozo** [comment]
quick fix maybe (and incoming facepalm for myself): create an empty `prefs.properties` file near the jar file

**Comment by serifpersia** [comment]
image

Disabling the load func from fileManager solves the main func to not go in debug mode but sadly I still don't see the tool if I try to build it. I tried to remove all code from filemanager class and it seems to make the tool visible again so I assume something is not right in that class file with your new modifications. Does it work for you without issue? I do have latest jdk 8 and I didn't have such issue before. I did make empty properties file thinking it doesn't load the jar plugin because of properties file not being found but thats not it clearly. Maybe some code that looks for board info and esp32 sdk and location has be compatible on any system. I will test with mentioned jdk to see if there is any difference.
EDIT: Running Arduino IDE using console I see this, the Arduino IDE doesn't crash but the tool is not loaded! Seems to be windows dir related? /C:/Users/redacted/Documents/Arduino/tools/ESP32PartitionTool/tool/ESP32PartitionTool.jar the / before C is probably the issue here

``
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/redacted/Documents/Arduino/tools/ESP32PartitionTool/tool/ESP32PartitionTool.jar
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at com.serifpersia.esp32partitiontool.FileManager.<init>(FileManager.java:73)
        at com.serifpersia.esp32partitiontool.ESP32PartitionTool.init(ESP32PartitionTool.java:63)
        at processing.app.Editor.addTools(Editor.java:884)
        at processing.app.Editor.buildToolsMenu(Editor.java:731)
        at processing.app.Editor.buildMenuBar(Editor.java:543)
        at processing.app.Editor.<init>(Editor.java:290)
        at processing.app.Base.handleOpen(Base.java:882)
        at processing.app.Base.handleOpen(Base.java:868)
        at processing.app.Base.handleOpen(Base.java:864)
        at processing.app.Base.handleNew(Base.java:803)
        at processing.app.Base.<init>(Base.java:491)
        at processing.app.Base.main(Base.java:150)
        ``

**Comment by tobozo** [comment]
apparently on windows the unwanted `/` path prefix is caused by classPath:

```java
String classPath = FileManager.class.getProtectionDomain().getCodeSource().getLocation().getPath();
Path path        = Paths.get(classPath); 
```

It's an ugly fix but maybe blindly stripping the first character can fix that:

```java
Path path        = Paths.get( isWindows ? classPath.substring(1) : classPath );
```

**Comment by serifpersia** [comment]
> apparently on windows the unwanted `/` path prefix is caused by classPath:
> 
> ```java
> String classPath = FileManager.class.getProtectionDomain().getCodeSource().getLocation().getPath();
> Path path        = Paths.get(classPath); 
> ```
> 
> It's an ugly fix but maybe blindly stripping the first character can fix that:
> 
> ```java
> Path path        = Paths.get( isWindows ? classPath.substring(1) : classPath );
> ```

Yeah looks like that solved the issue. But java class handling paths should handle windows why does it start with /
Found a better fix we dont use toString()

```java
	String classPath = FileManager.class.getProtectionDomain().getCodeSource().getLocation().getPath();
	Path path = Paths.get(classPath);
	String classDir = path.getParent().toString();
	String propertiesFile = classDir + "/prefs.properties";
```

```java
	String classPath = FileManager.class.getProtectionDomain().getCodeSource().getLocation().getPath();
	File classFile = new File(classPath);
	String classDir = classFile.getParent();
	String propertiesFile = classDir + "/prefs.properties";
```

**Comment by tobozo** [comment]
ah thanks for the fix :+1: 

I'm not sure why it does this, maybe one of the chained methods [doesn't empathize with newer versions of Windows](https://stackoverflow.com/questions/66548704/why-path-of-java-class-file-starts-with-slash-on-windows-10).

anyway, I'll now try to experiment with the JScrollPane and visible/hidden strategy, wish me luck :crossed_fingers:

**Comment by tobozo** [comment]
Although this a major refactor, not much has visually changed, or so I hope.

image

Here's a summary of the last changes:

- root frame size is now fixed (resize problems across platforms)
- scrollbar is default hidden (fits to heigh) when csv has less than 15 items
- rows list can store up to 100 entries
- new Class `CSVRow` with public properties for each cell
  - `size` field now restricted to numbers
  - `size` field recalculates offsets on any change
  - `checkbox` adds or removes a row when toggled
- a new png asset has been added in `resources` folder
- an additional classpath to the `resources` folder has been set in `build.sh`
- new `About` button (also rate my HTML skills :rofl:)

image

**Comment by serifpersia** [comment]
Since your changes no longer allow my tool to be tested inside IDE I removed the main func code, if you could maybe fix that in the future its tiresome to build the tool and see the minor ui changes in Arduino IDE instead in Java IDE.  Let me know when you have your last commit in this PR I will update the About image visuals as well as modify the formatting on the class files but if you can do it on your end it would be appreciated.  The tool didn't work because of that warning sign you had inside a comment in FileManager class text encoding didn't fix it so I removed that from the comment (:

**Comment by tobozo** [comment]
Sorry about breaking the commented function, I had no clue how to test it so I ignored it in my tests.

> its tiresome to build the tool and see the minor ui changes in Arduino IDE instead in Java IDE

haha I've been doing this all along with a KDE's text editor, the compiler doesn't seem to complain so could it be a problem caused by vsCode, Eclipse or whatever IDE?

Latest changes:

- enforced some validation/sanitazing behaviours for cell values during csv import
- made the label text on top of the partition list show the csv filename instead of "Partitions", there may be a better place for that.
- the "SPIFFS" panel get its title, combo and button-label change dynamically with the detected filesystem in the csv data (subtypes 0x81, 0x82, 0x83 for fat/littlsfs/spiffs)
- the offsets are recalculated as often as possible
- if a cell has an invalid value, the text becomes red
- on cvs import: types/subtypes numeric values are translated to words when applicable
- the shrug.png is intended to be replaced, however there's also some uncolonized free area in the UI, under the SPIFFS tools, there's about 170px*384px to fit a visual, logo or photo

**Comment by tobozo** [comment]
Foxusing on the Arduino IDE 1.8.x features, according to platform.txt a couple of things can be overriden directly from the sketch folder, and it takes precedence on the board settings: 

- partitions.csv
- bootloader.bin

image

One possible workflow: 

1) Select a Partition Scheme from the Arduino IDE Tools menu to be used as a template.
2) Open the ESP32PartitionTool applet, it'll automatically import the CSV file selected in the Arduino IDE Tools menu.
3) Modify the partition table as needed.
4) Use a special button "Save CSV to sketch folder", only confirm if overwriting an existing partitions.csv file.
5) Compile the sketch, the partitions.csv file from the sketch folder will be used instead of the one selected from the Tools menu.
6) Rinse and repeat.

**Comment by serifpersia** [comment]
> Foxusing on the Arduino IDE 1.8.x features, according to platform.txt a couple of things can be overriden directly from the sketch folder, and it takes precedence on the board settings:
> 
>     * partitions.csv
> 
>     * bootloader.bin
> 
> 
> image
> 
> One possible workflow:
> 
>     1. Select a Partition Scheme from the Arduino IDE Tools menu to be used as a template.
> 
>     2. Open the ESP32PartitionTool applet, it'll automatically import the CSV file selected in the Arduino IDE Tools menu.
> 
>     3. Modify the partition table as needed.
> 
>     4. Use a special button "Save CSV to sketch folder", only confirm if overwriting an existing partitions.csv file.
> 
>     5. Compile the sketch, the partitions.csv file from the sketch folder will be used instead of the one selected from the Tools menu.
> 
>     6. Rinse and repeat.

If you select the Huge App partition scheme Arduino IDE uses partitions.csv file in the sketch directory otherwise it will use the Huge App partitions.csv from esp32 sdk. Maybe auto select this partition scheme when you open the tool? Can the tool do this? Minimizing user input is always good.

**Comment by tobozo** [comment]
> Maybe auto select this partition scheme when you open the tool? 

I just needed your confirmation on the precedence order before doing that, will ship with the next commits.

Current task: remotely trigger the `build project` action in Arduino IDE when the build folder doesn't exists. Since it's always picking up files based on the latest build, it feels reasonable to trigger the build from the applet.

**Comment by serifpersia** [comment]
Feel free to suggest the workflow you think its optimal for this tool use case. As I said automatic setting of Huge App partitions scheme or any other way Arduino IDE will let you use the custom partitions csv file in the sketch directory will be good for end users it eliminates extra clicks and menu's users have to manually put input effort into.

**Comment by tobozo** [comment]
ah nice to hear, I wasn't sure about my understanding of the applet's scope after breaking the commented out function in ESPPartitionTool.java ^^

current task: partitions.csv overwrite confirmation dialog with "remember my decision" checkbox

image

**Comment by tobozo** [comment]
Latest changes:

- more healths check on applet start (less checks later)
- better format fo output csv 
- pref checkbox: confirm creation of empty spiffs.bin when no /data folder exists
- pref checkbox: overwrite without confirmation partitions.csv
- partitions.csv search order: sketch folder first
- bootloader.bin search order and build: getBootloaderImagePath()

I am not happy with the new checkboxes, had to make the label shorter otherwise it would en up overflowed and not visible, I'll probably move these to a settings panel but we need to discuss this before going further.

### Settings panel request for comments:

New button with no text, just a gear icon.

image

Pushing the button opens a popup panel with `save` / `cancel` and the following editable options:

  - CSV overwrite checkBox (checked = no confirmation asked, toggled by "remember my choice" in dialog)
  - SPIFFS empty warning (checked = prompt for creating or aborting)
  - Debug (checked = enabled)
  - full path to mklittlefs + FileDialog
  - full path to mkspiffs + FileDialog
  - full path to mkfatfs + FileDialog
  - full path to esptool + FileDialog
  - another "About" button
  - more options ....

**Comment by serifpersia** [comment]
Yeah single button opening new panel for those option sounds good. I'm not sure what do you mean when you list the paths for the tools. Why does the user need to see this?

**Comment by tobozo** [comment]
if all values extracted from `BaseNoGui` can also be maintained from a settings panel, then the applet can optionnally work without the Arduino IDE.

btw I've tried to restore the `main()` function in ESP32PartitionTool class but I still get the `no main manifest attribute` or `Could not find or load main class` error so that's as far as I can go.

**Comment by tobozo** [comment]
The panel is ugly but it's working, and I have struggled with `GridBagLayout` long enough to strongly believe it should be called `ScumbagLayout` :-)

 image

**Comment by serifpersia** [comment]
> The panel is ugly but it's working, and I have struggled with `GridBagLayout` long enough to strongly believe it should be called `ScumbagLayout` :-)
> 
> image

Yeah I avoid using gridbag layout at all cost its really a pain. I once used it in my main panel for my app and it was a mess not scaling the same on different platforms, so borderlayout, gridlayout and flowlayout are my top picks for swing. Use gridbag if you want pain in your life : P
EDIT: I pulled your latest changes seems like the tool works as expected in Arduino IDE. It doesn't seem to work in eclipse so I would just give up on that unless you want to install Eclipse IDE for java development, and import the maven project and execute maven test and and go from there. You brought a lot of changes so I don't think I have time or motivation to try and bring back that functionality.  I added that main call so you could test your change without building  & trying it on Arduino IDE, the arduino and processing imports don't even work so you wouldn't be able to test those functions of the tool but for UI it was useful to see your UI change faster. I don't mind it since for me the tool's UI is mostly there. So yeah I wouldn't worry about it

**Comment by tobozo** [comment]
well I don't think I'll have much to add after this push

- Settings panel is now a popup window
- Help panel is now a popup window
- General panel has a background image

image


image

now the apps needs a logo to replace `shrug.png`

image


if you plan to pick a different background image for the main panel, it can be of any size and it'll be stretched to fit, but keep in mind that image must have a very high luminosity otherwise the text will become unreadable.

**Comment by serifpersia** [comment]
Appreciate the commits. I will test the latest changes tomorrow and modify if needed. Imagery will be replaced I will put some time into making a logo for this in gimp of course. If you don't plan to commit anymore on this pull let me know I will probably do final touch up tomorrow and accept it if its all working well.

**Comment by tobozo** [comment]
yep I have no further commits for this PR

**Comment by serifpersia** [comment]
Changes verified, tool is in working state ready for release. Once again I really appreciate your contribution to the project. Thanks!

**Comment by tobozo** [comment]
you're welcome! 

if you have detailed instructions on how to compile, lint, verify and create the release package, it can eventually be automated with a github workflow:

- on commit/PR/push => build the project (XLint/debug)
- on new tag/release => build the project(release/verify) + build the package + publish the package

then all you have to do is create a new release from github webapp and wait for the workflow to build the jar, zip it and add it as an asset to the release it's being tagged with

**Comment by serifpersia** [comment]
> you're welcome!
> 
> if you have detailed instructions on how to compile, lint, verify and create the release package, it can eventually be automated with a github workflow:
> 
>     * on commit/PR/push => build the project (XLint/debug)
> 
>     * on new tag/release => build the project(release/verify) + build the package + publish the package
> 
> 
> then all you have to do is create a new release from github webapp and wait for the workflow to build the jar, zip it and add it as an asset to the release it's being tagged with

Yes I'm looking into automation I always do manual releases zipping jars and so on. For this project all we have to do is run the .sh script and zip the folder and do a new release. I'm going to experiment on this but I already did release it manually (:

**Comment by tobozo** [comment]
yes the build.sh is relevant for building a release package, but more can be done for the other situations.

Local development, pushes, commits and pull requests may need a dedicated build strategy with additional checks (e.g. unused imports, warnings to suppress).

**Comment by tobozo** [comment]
btw it's bad practice to replace assets in an existing release rather than creating a new tag and a new release

whomever downloaded the version from last week has no way of knowing it changed

also you lose history: maybe in some situations the older version could work where the newer wouldn't (old but not obsolete :robot: )

**Pull request merged**
