### PR TITLE
Dual platformio/arduino support

### PR DESCRIPTION
**Pull request by tobozo**
ref #4  

Summary of changes:

- Added github workflows to automate the building of both Arduino IDE and Platformio package:
  - On commit, push, pull request
    - Build project
  - On release.publish
    - Build project
    - Create Platformio and Arduino zip files
    - Add both Plarformio and Arduino zip files to the release page
    - TODO: publish package to platformio registry
- Arduino class ``ESP32PartitionTool` is the default runnable
- Platformio class `ESP32PartitionToolStandalone` is an optional runnable 
- Create Bin, Merge Bin, SPIFFS and log panels have been removed from both contexts.
- Added package.json to build a platformio-compatible tool package
- Added esp32partitiontool.py as a component of the platformio package
- Modified ReadMe to document the process (some URLs will need editing):

## Installation (Platformio)

- Install Java and make sure the executable is in the path
- Create a `partition_manager.py` in your project folder

#### partition_manager.py

```python
Import('env')
import os.path
import sys

# add esp32partitiontool to path
sys.path.append(os.path.abspath( env.PioPlatform().get_package_dir("tool-esp32partitiontool") ))
# import module
from esp32partitiontool import *
# run module
load_pm(env)
```

- Add a special environment `build-partition` to launch the GUI, both `extra_scripts` and `platform_packages` entries must be set

#### platformio.ini

```ini
[env]
framework              = arduino
platform               = espressif32
board                  = m5stack-cores3
board_build.partitions = partitions/partitions-16MB-factory-4-apps.csv

[env:build-partition]
extra_scripts          = partition_manager.py
platform_packages      = tool-esp32partitiontool @ https://github.com/serifpersia/esp32partitiontool/releases/download/v1.4/esp32partitiontool-platformio.zip
```

- If building the plugin from source, remove the URL from the `platform_packages` entry ...

```ini
platform_packages      = tool-esp32partitiontool
```

- ... and use `pio pkg` to install the plugin from the root of your platformio project:

```shell
pio pkg install -e build-partition --no-save --tool /path/to/esp32partitiontool/esp32partitiontool-platformio.zip --force
```

## Usage (Platformio)

- Build the `build-partition` Platformio environment from your IDE or use the shell: `pio run -e build-partition`

### CODE REVIEW

**Comment by tobozo** [comment]
@serifpersia there are so many commits in this PR it'll probably be a good idea to use the `squash and merge` option.

[this is what the release page looks like](https://github.com/tobozo/esp32partitiontool/releases/tag/v1.4.1) on my fork, the additional zip files have been automatically built by the github workflow right after I've created and tagged the release.

The `version` value in the package.json file should always match the next version number, it's easy to forget about that detail before creating a new release. Failure to increment properly the version will result in a package being simply ignored.

Once the new scripts and workflow will be merged on the main branch, the release creation procedure will be as follows:

1) Check that all the commits are in order on the main branch
2) Choose a **new version number** (e.g. semver-increment the latest version from the releases page)
3) In package.json update the value of `version` to the **new version number**
4) Go to the releases page and click on `Draft a new release`
5) Click on `Choose a tag` and enter the **new version number**, then click on `Create new tag ...`
image
6) Click on `Publish Release` and **wait for the workflow to execute** (~2mn)  until the files are added
image

**Comment by serifpersia** [comment]
Looking forward to try the changes. Is the platformio universal ie works on windows as well? I've seen you set it to linux package in json file does it matter? I know that for each os each framework downloads specific files example for windows esptool.exe and linux sdk has esptool.py. Are the build scripts for tool building for Arduino IDE still functional on their own? Let me know when your changes are finalized and please provide detailed instructions on how to configure and use the tool I'm not familiar with platformio but I do have VSCode & PlatformIO installed, so I have to make sure it works on both systems before merging.

**Comment by tobozo** [comment]
> Is the platformio universal ie works on windows as well? 

Probably, unless platform packages marked for linux only in their json file are ignored by other OS ?

This tool isn't enumerated in espressif32 platform.json file anyway, so there's no real platform or OS dependency, it's only pulled as standalone because the url to the zip file is provided in the platformio.ini (also it probably doesn't need much to become esp8266 compatible)

> Are the build scripts for tool building for Arduino IDE still functional on their own

Only build.sh has been modified to re-use the CI scripts in the .github folder (don't edit those); it's untested on mac and the .bat file probably needs an update

The build process isn't much different though, it's only using a ClassList file because the java files are now spread in three different folders:

```shell
# Find all Java files and export the list in a ClassList file
find src/main/java/com -name "*.java" > ClassList
# Maximum linting
javac -Xlint -cp "dependencies/*" -d "bin" @ClassList
# Copy resources directory contents into the bin folder
cp -r src/main/resources/* bin/
# Create the JAR file
jar cfe build/ESP32PartitionTool.jar com.serifpersia.esp32partitiontool.ESP32PartitionTool -C bin . 
```

Launching the platformio version requires a specific call:

```shell
java -cp build/ESP32PartitionTool.jar com.serifpersia.esp32partitiontool.ESP32PartitionToolStandalone
```

Detailed instructions on how to use the tool are in the issue #4 

- Create a hello world platformio project for esp32
- Create a `partition_manager.py` file in the project folder
```python
Import('env')
import os.path
import sys

# add esp32partitiontool to path
sys.path.append(os.path.abspath( env.PioPlatform().get_package_dir("tool-esp32partitiontool") ))
# import module
from esp32partitiontool import *
# run module
load_pm(env)
```
- Make sure the hello world profile (ini values for platform, board, etc) is under the `[env]` section of your platformio.ini so it'll be inherited by all other environments
- Add an extra environment `[env:build-partition]`:
```ini
[env:build-partition]
extra_scripts          = partition_manager.py
platform_packages      = tool-esp32partitiontool @ https://github.com/tobozo/esp32partitiontool/releases/download/v1.4.1/esp32partitiontool-platformio.zip
```

- Select `build-partition` environment and run the task `edit_partition` ( same as using the shell command: `pio run -e build-partition -f edit_partition`)

> Let me know when your changes are finalized 

The app state isn't final as some minor design issues still need to be addressed (e.g. font grease seems wrong in the standalone version, and build scripts haven't been adjusted for MacOS/Windows), but the jar file and the zip packages are working so I'll say this "arduino/platformio" iteration is finalized.

It has not been determined how (and if) the package will be submitted to the platformio registry though.

https://docs.platformio.org/en/stable/core/userguide/pkg/cmd_publish.html

Publishing manually to platformio registry is possible but requires specific conditions e.g. platformio account, being 'logged in', and a very specific folder layout or a pre-baked zip archive. 

Fortunately it can be automated with a platformio token, here's an example of a workflow to auto-publish a library when a new release becomes available:

https://github.com/lovyan03/LovyanGFX/blob/master/.github/workflows/pioPkgPublish.yml

Now it's up to you to decide if you want esp32partitiontool to be in the platformio registry, and if you want new package releases to be published automatically or manually.

**Comment by serifpersia** [comment]
With changes to json file I managed to confirm it working. The example project is updated as per your simpler suggestion. The version is going to be x.x so after this pull merge the new release will be 1.4. And yes manual updating the tool is fine I don't see any issues with it users will just have to use the correct url found in example project as well as in readme or use own built tool. 
Feel free to remove the Arduino IDE related stuff and fix the UI in standalone not matching with the Arduino IDE style.  I will try to fix the bat script and see if the build.sh still works fine for Arduino IDE tool building. After all that is fixed and modified and updated the pull will be ready for merge and the repo will be updated with auto generated 1.4 release after the merge.

**Comment by serifpersia** [comment]
I used your build.sh script and I see build and temp folders. I used tool from temp folder and it seems like arduino version no longer has the spiffs and merge UI anymore? Keep in mind we don't want to remove this from arduino ide tool.

**Comment by tobozo** [comment]
yep this was in the initial post of this PR:

- Create Bin, Merge Bin, SPIFFS and log panels have been removed from both contexts.

The code is only commented out so the functions are still there. Why is it so needed on Arduino IDE? 

Filesystem build and upload tools are packages of the espressif32 platform, and they're already available separately with both Arduino IDE (as java plugins) and Platformio (as targets).

**Comment by serifpersia** [comment]
Let me know if the PR is ready. I cleaned up the code base fixed UI, all thats left is to sort out script files. I will add back SPIFFS and merge back as a separate panel with a button press in the future but for now this is fine older version can be still used for that needs. Yes the tools are there but they aren't in the UI of Arduino IDE. I don't care about PlatformIO ESP32 sdk tools, the tool in Arduino IDE will have SPIFFS, Merge create and upload somewhere inside of the tool because some users might find it convenient to do those commands from UI and not some cli.  Anyways let me know if this is ready. I don't think there is anything else to do for the CL.

**Comment by tobozo** [comment]
ok that was my last commit (fix the broken platformio support resulting from the URN change) and as far as I'm concerned this iteration is complete :+1:

**Comment by serifpersia** [comment]
I've updated the local tool building scripts. I will attempt to create a release hopefully it will work. I'm merging it.
Thanks for the PR once again!

**Comment by tobozo** [comment]
the yml only publishes the platformio package but specifies a zip name different from the one that's generated, so only half the job is done:

##### create_arduino_package.sh
     archive_file="ESP32PartitionTool-Arduino.zip"

**Comment by tobozo** [comment]
the file names in the "Upload artifact" yml task must match the file names from the create_*package.sh files


[edit] and the worfklow worked just fine without token

image


image

**Pull request merged**
